### PR TITLE
Set correct path to splash-nww in the polygons example

### LINKED ISSUE #308: Polygons example image location is incorrect
### Description
One of the polygons (the one located over Texas, Oklahoma and Arkansas) isn't loading its corresponding texture. Console produces the following error:
`GET http://127.0.0.1:8080/images/400x230-splash-nww.png 404 (Not Found)` (assuming execution from a local web server).

The same texture is correctly loaded elsewhere in the same example. This is because the correct address is:
`/examples/data/400x230-splash-nww.png`

### Operating System and Version

Windows 10, Chrome 62.0.

### PR DESCRIPTION
**Pull request by AkeluX**
Closes #308 for release

### CODE REVIEW

File: examples/Polygons.js [hunk 1]
```diff
@@ -145,7 +145,7 @@ requirejs(['./WorldWindShim',
         ];
 
         polygonAttributes = new WorldWind.ShapeAttributes(null);
-        polygonAttributes.imageSource = "../images/400x230-splash-nww.png";
+        polygonAttributes.imageSource = "../examples/data/400x230-splash-nww.png";
```
Comment (Beak-man) [inline examples/Polygons.js]: I mentioned in the issue the full path of the file, but using the relative "data/400x230-splash-nww.png" suffices, as it's seen in lines 106, 205, etc.
