### PR TITLE
Bug/#168 SurfaceShapes state updating propagation

### LINKED ISSUE #168: Various surface shape property changes do not fully propogate
`SurfaceCircle`, `SurfaceEllipse`, `SurfaceRectangle` cannot be updated after creation.

Firstly, `SurfaceEllipse` and `SurfaceRectangle` do not sufficiently dirty themselves when their property setters  are invoked: they set `this.stateKeyInvalid = true`, but should also set `this._boundaries = null` and `this.isPrepared = false` to allow their boundaries to be recomputed.

`SurfaceCircle` has this problem as well, but furthermore should also update its base ellipse's `this._majorRadius` and `this._minorRadius` when its `radius` property setter is invoked.

### PR DESCRIPTION
**Pull request by Beak-man**
### Description of the Change
As reported on #168, `SurfaceCircle`, `SurfaceEllipse` and `SurfaceRectangle` had issues while updating their state. An example was done that exposes this. At the same time, an investigation was done to review if other SurfaceShapes (`SurfacePolyline`, `SurfacePolygon` and `SurfaceSector`) had related issues. While testing, it was found that `SurfaceSector` was not updating either, as the class lacked setters to be able to mutate. This PR addresses these SurfaceShapes updating issues.

### Why Should This Be In Core?
It's a necessity for Web WorldWind to have SurfaceShapes that are able to update their state. Most of these were already designed to do it, they only needed to properly set their dirty flags in order to do so.

### Benefits
- The state of the three SurfaceShapes mentioned in issue #168 can now be updated via a function on parent class `SurfaceShape`. It doesn't affect the mutability of `SurfacePolyline` and `SurfacePolygon`, which were updating OK before this fix.
- `SurfaceSector ` now has an `Object.defineProperties()` function and is able to receive a `Sector` to update its state.
- Changes the `isPrepared` flag of parent class `SurfaceShape` to the more descriptive name `boundariesArePrepared`.

### Potential Drawbacks
- `SurfaceCircle` needs to set properties of its parent class `SurfaceEllipse` for its state to update. Issue #255 was made to address this.
- It may be a good idea to add `this.stateKeyInvalid = true` to the new `resetBoundaries()` function of `SurfaceShape` to further simplify code in the children classes' setters (this was tested and it works).
- The included example `TestMovingSurfaceShapes` was intended at first only for bug hunting purposes and it grew quite long. It may be desirable to simplify it or remove it altogether before committing it to the repo.

### Applicable Issues
Closes #168, #236, #240, and #241.

### CODE REVIEW

File: src/shapes/SurfacePolyline.js [hunk 1]
```diff
@@ -101,5 +101,10 @@ define([
             return SurfacePolyline.staticStateKey(this);
         };
 
+        // Internal. Polyline doesn't generate its own boundaries. See SurfaceShape.prototype.computeBoundaries.
+        SurfacePolyline.prototype.computeBoundaries = function(dc) {
+            return;
```
Comment (pdavidc) [inline src/shapes/SurfacePolyline.js]: Same comment for the unnecessary return in SurfacePolygon.prototype.computeBoundaries.

File: src/shapes/SurfaceEllipse.js [hunk 2]
```diff
@@ -85,6 +85,8 @@ define([
                 },
                 set: function(value) {
                     this.stateKeyInvalid = true;
+                    this.resetBoundaries();
+                    // this._boundaries = null;
```
Comment (pdavidc) [inline src/shapes/SurfaceEllipse.js]: What's the motivation for leaving this in? If it's no longer necessary, remove it. Commented out code leaves room for ambiguity in future development.

Comment (Beak-man) [reply src/shapes/SurfaceEllipse.js]: I intended to remove them, but I mistook while searching for them. Will do.
