### PR TITLE
Fix Atmosphere initial state example

### LINKED ISSUE #291: Atmosphere example starts with day/night atmosphere
### Description

The work conducted to resolve #100 now shows the day/night transition on the initiation of the example instead of the pure Atmosphere display. The pure atmosphere display is still available if you cycle the "Sun Simulation"

### Steps to Reproduce

1. Open the Atmosphere example (notice there is a shadow and night)

**Expected behavior:** [What you expect to happen]

Should show the atmosphere effect without the night portions

**Actual behavior:** [What actually happens]

On initial load, the sun position is defined through the specification of Layer time property.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time

### Operating System and Version

OSX - Chrome

### Additional Information

I introduced this bug when I was working on #100 and noticed the effect today.

### PR DESCRIPTION
**Pull request by zglueck**
### Description of the Change

Remove the assignment of the current time to the `time` property of the layer thus preventing the determination of the sun position and display showing the day/night display instead of the pure atmosphere effect.

### Why Should This Be In Core?

Returns the example to the original version.

### Applicable Issues

Closes #291

### CODE REVIEW

File: examples/Atmosphere.js [hunk 1]
```diff
@@ -27,7 +27,6 @@ requirejs(['./WorldWindShim',
         
         var atmosphereLayer = new WorldWind.AtmosphereLayer();
         var timeStamp = Date.now();
```
Comment (pdavidc) [inline examples/Atmosphere.js]: The declaration and initialization of timeStamp seems out of place. Is there a better location?

Comment (zglueck) [reply examples/Atmosphere.js]: Yes, I think line 36 would be better. It would be grouped with the other variables declared for the simulation component.
