### PR TITLE
Repaired Text picking

### LINKED ISSUE #333: ScreenText example picking not working
### Description

In the ScreenText example, picking only works on the center text and not on the text in the corners. In addition, when the center text is picked the following error is displayed in the console:

WARNING: there is no texture bound to the unit 0

### Operating System and Version

Ubuntu 16.04/Chrome 61

### PR DESCRIPTION
**Pull request by pdavidc**
- Both GeographicText and ScreenText picking failed when the value of BasicTextureProgram.opacity was anything other than 1.0.
- BasicTextureProgram is a shared WebGL shader program, which therefore shares its variable state with all drawing code that uses the program. Drawing code in one layer/shape can affect the drawing code of another when care is not taken to set all state appropriately for the current draw call.
- Modified Text to explicitly set BasicTextureProgram.opacity to 1.0 during picking.
- Consolidated unnecessarily repeated WebGL calls
- Collapsed unnecessarily nested control flow
- Grouped related WebGL calls
- Closes #333

### CODE REVIEW

**Comment by markpet49** [comment]
@pdavidc On Ubuntu/Firefox: The fix works flawlessly. On Ubuntu/Chrome: Picking works flawlessly, but I still see the error message:
[.Offscreen-For-WebGL-0x3497eda66000]RENDER WARNING: there is no texture bound to the unit 0
I am satisfied with the fix, as is, if you are. I believe we have a backlog task to address this Chrome warning.

File: src/shapes/Text.js [hunk 1]
```diff
@@ -492,10 +494,7 @@ define([
                 program.loadModelviewProjection(gl, Text.matrix);
 
                 // Set the pick color for picking or the color, opacity and texture if not picking.
```
Comment (AkeluX) [inline src/shapes/Text.js]: This comment could be adapted to the change.

File: src/shapes/Text.js [hunk 2]
```diff
@@ -468,6 +468,8 @@ define([
 
             if (dc.pickingMode) {
                 this.pickColor = dc.uniquePickColor();
+                program.loadColor(gl, this.pickColor);
+                program.loadOpacity(gl, 1);
             }
 
             // Compute the effective visibility. Use the current value if picking.
```
Comment (AkeluX) [inline src/shapes/Text.js]: This isn't part of the fix, but there could be an `else` here instead of the second if. The comment is also detached from part of the logic, which is above.

**Comment by pdavidc** [comment]
@markpet49 We do indeed have backlog task #302 that captures the WebGL texturing binding warnings.

@AkeluX My original take at this was to limit changes to an absolute minimum. That said, the stale comments and odd disjointed if/if statements have convinced me otherwise. I'll take the time to adjust the comments and the control flow to be more appropriate for the new logic.

**Comment by pdavidc** [comment]
@markpet49 @AkeluX Please take a look at the latest version of this pull request. In light of @AkeluX's recommendations I've performed a light refactoring of Text's drawing code with the following intentions:
• Consolidate unnecessarily repeated WebGL calls
• Collapse unnecessarily nested control flow
• Group related WebGL calls
